{{- if and .Values.configFromSecret .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configFromSecret }}
  labels:
    {{- include "casdoor.labels" . | nindent 4 }}
type: Opaque
data:
  app.conf: |
    {{- tpl .Values.config . | nindent 4 }}
{{- end }}