name: Build

on:
  push:
    branches:
      - master

jobs:
  release-and-push:
    name: Release And Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: -1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup
        run: npm install

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
